version: "3.3"

services:
  benerbij-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "benerbij-backend"
    container_name: "loopmeestersbenerbij-backend"
    volumes:
      - "./sqlite_db:/application/sqlite_db"
      - "./data_api_endpoints:/application/data_api_endpoints"


    networks:
      - traefik_service

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_service"


      - "traefik.http.services.benerbij-backend.loadbalancer.server.port=8000"

      - "traefik.http.routers.benerbijbackend-admin.rule=Host(`ben-erbij.guidodiepen.nl`) && (Path(`/api/polls`) || Path(`/api/polls/`))"
      - "traefik.http.routers.benerbijbackend-admin.entrypoints=websecure"
      - "traefik.http.routers.benerbijbackend-admin.middlewares=myauth1"
      - "traefik.http.routers.benerbijbackend-admin.tls=true"
      - "traefik.http.routers.benerbijbackend-admin.tls.certresolver=myresolver"
      - "traefik.http.routers.benerbijbackend-admin.service=benerbij-backend"
      - "traefik.http.middlewares.myauth1.basicauth.users=${HTTP_PASSWD}"


      - "traefik.http.routers.benerbijbackend.rule=Host(`test-auth-ben-erbij.guidodiepen.nl`) && ( PathPrefix(`/api`) || PathPrefix(`/static`) || PathPrefix(`/docs`) || PathPrefix(`/openapi.json`)) && !(Path(`/api/polls`) || Path(`/api/polls/`))"
      - "traefik.http.routers.benerbijbackend.entrypoints=websecure"
      - "traefik.http.routers.benerbijbackend.tls=true"
      - "traefik.http.routers.benerbijbackend.tls.certresolver=myresolver"
      - "traefik.http.routers.benerbijbackend.service=benerbij-backend"













  benerbij-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "benerbij-frontend"
    container_name: "loopmeestersbenerbij-frontend"


    networks:
      - traefik_service

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.benerbijfrontend.rule=Host(`ben-erbij.guidodiepen.nl`)"
      - "traefik.http.routers.benerbijfrontend.entrypoints=websecure"
      - "traefik.http.routers.benerbijfrontend.tls=true"
      - "traefik.http.routers.benerbijfrontend.tls.certresolver=myresolver"
      - "traefik.http.services.benerbijfrontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_service"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"




networks:
  traefik_service:
    external: true
