version: "3.3"

services:
  benerbij-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./sqlite_db:/application/sqlite_db"
      - "./data_api_endpoints:/application/data_api_endpoints"


    networks:
      - traefik_service

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_service"


      - "traefik.http.services.benerbij${ENVIRONMENT}-backend.loadbalancer.server.port=8000"

      - "traefik.http.routers.benerbij${ENVIRONMENT}backend-admin.rule=Host(`${TRAEFIK_DOMAIN}`) && (Path(`/api/polls`) || Path(`/api/polls/`))"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend-admin.entrypoints=websecure"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend-admin.middlewares=myauth${ENVIRONMENT}"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend-admin.tls=true"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend-admin.tls.certresolver=myresolver"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend-admin.service=benerbij${ENVIRONMENT}-backend"
      - "traefik.http.middlewares.myauth${ENVIRONMENT}.basicauth.users=${HTTP_PASSWD}"


      - "traefik.http.routers.benerbij${ENVIRONMENT}backend.rule=Host(`${TRAEFIK_DOMAIN}`) && ( PathPrefix(`/api`) || PathPrefix(`/static`) || PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend.entrypoints=websecure"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend.tls=true"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend.tls.certresolver=myresolver"
      - "traefik.http.routers.benerbij${ENVIRONMENT}backend.service=benerbij${ENVIRONMENT}-backend"







  benerbij-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      API_USER: "${API_USER}"
      API_PASSWD: "${API_PASSWD}"


    networks:
      - traefik_service

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.benerbij${ENVIRONMENT}-frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_service"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"


      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend-admin.rule=Host(`${TRAEFIK_DOMAIN}`) && (Path(`/`) || PathPrefix(`/create-poll`))"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend-admin.entrypoints=websecure"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend-admin.tls=true"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend-admin.tls.certresolver=myresolver"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend-admin.service=benerbij${ENVIRONMENT}-frontend"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend-admin.middlewares=myauth${ENVIRONMENT}"
        #- "traefik.http.middlewares.myauth${ENVIRONMENT}.basicauth.users=${HTTP_PASSWD}"

      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend.entrypoints=websecure"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend.tls=true"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.benerbij${ENVIRONMENT}frontend.service=benerbij${ENVIRONMENT}-frontend"


networks:
  traefik_service:
    external: true
